[phases.setup]
nixPkgs = ["...", "postgresql"]

[phases.build]
cmds = ["bundle install", "bundle exec rails assets:precompile"]

[start]
cmd = "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p $PORT"