development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "dev_secret_key_base_for_la_bonne_cuisine_development_environment" %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "test_secret_key_base_for_la_bonne_cuisine_test_environment" %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>